import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { Suspense } from "react";
import Providers from "./providers";
import ConnectWallet from "./components/ConnectWallet";
import NavLinks from "./components/NavLinks";
import VaultSelector from "./components/VaultSelector";
import NetworkBadge from "./components/NetworkBadge";
import VaultProviderWrapper from "./vault-provider-wrapper";
import VaultVersionGate from "./vault-version-gate";
import { auth } from "@/auth";
import AccountMenu from "./components/AccountMenu";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const googleAuth = process.env.GOOGLE_AUTH === "true";
  const session = googleAuth ? await auth() : null;
  const showChrome = !googleAuth || Boolean(session?.user?.email);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {showChrome ? (
          <Providers>
            <Suspense fallback={null}>
              <VaultProviderWrapper>
                <header className="border-b border-neutral-200 bg-white dark:border-neutral-800 dark:bg-neutral-900">
                  <nav className="mx-auto flex max-w-7xl items-center gap-6 px-4 py-3">
                    <Link
                      href="/"
                      className="text-sm font-semibold text-neutral-900 dark:text-white"
                    >
                      Harmonix
                    </Link>
                    <NavLinks />
                    <div className="ml-auto flex items-center gap-3">
                      <VaultSelector />
                      <NetworkBadge />
                      <ConnectWallet />
                      {session?.user && (
                        <AccountMenu
                          name={session.user.name}
                          image={session.user.image}
                        />
                      )}
                    </div>
                  </nav>
                </header>
                <VaultVersionGate>{children}</VaultVersionGate>
              </VaultProviderWrapper>
            </Suspense>
          </Providers>
        ) : (
          children
        )}
      </body>
    </html>
  );
}
